### ISSUE TITLE
Error : Kompilasi ODKScan-Core di 64 Bit

### ISSUE THREAD

**Issue by wildanm** [openthinklabs/SmartOMR#7]
<strong>Sistem</strong>
# lsb_release --all

Distributor ID: Ubuntu
Description:    Ubuntu 13.10
Release:    13.10
Codename:   saucy

ODKScan-core# make
-D DEBUG_PROCESSOR -D DEBUG_ALIGN_IMAGE
g++ -Wall -c src/Addons.cpp -o src/Addons.o `pkg-config opencv --cflags --libs` -I./jsoncpp-src-0.5.0/include -I./src -I./ -I./zxing/core/src -I./zxing/cli/src -D DEBUG_PROCESSOR -D DEBUG_ALIGN_IMAGE
-D DEBUG_PROCESSOR -D DEBUG_ALIGN_IMAGE
g++ -Wall -c src/Aligner.cpp -o src/Aligner.o `pkg-config opencv --cflags --libs` -I./jsoncpp-src-0.5.0/include -I./src -I./ -I./zxing/core/src -I./zxing/cli/src -D DEBUG_PROCESSOR -D DEBUG_ALIGN_IMAGE
-D DEBUG_PROCESSOR -D DEBUG_ALIGN_IMAGE
g++ -Wall -c src/AlignmentUtils.cpp -o src/AlignmentUtils.o `pkg-config opencv --cflags --libs` -I./jsoncpp-src-0.5.0/include -I./src -I./ -I./zxing/core/src -I./zxing/cli/src -D DEBUG_PROCESSOR -D DEBUG_ALIGN_IMAGE
-D DEBUG_PROCESSOR -D DEBUG_ALIGN_IMAGE
g++ -Wall -c src/FileUtils.cpp -o src/FileUtils.o `pkg-config opencv --cflags --libs` -I./jsoncpp-src-0.5.0/include -I./src -I./ -I./zxing/core/src -I./zxing/cli/src -D DEBUG_PROCESSOR -D DEBUG_ALIGN_IMAGE
-D DEBUG_PROCESSOR -D DEBUG_ALIGN_IMAGE
g++ -Wall -c src/PCA_classifier.cpp -o src/PCA_classifier.o `pkg-config opencv --cflags --libs` -I./jsoncpp-src-0.5.0/include -I./src -I./ -I./zxing/core/src -I./zxing/cli/src -D DEBUG_PROCESSOR -D DEBUG_ALIGN_IMAGE
-D DEBUG_PROCESSOR -D DEBUG_ALIGN_IMAGE
g++ -Wall -c src/Processor.cpp -o src/Processor.o `pkg-config opencv --cflags --libs` -I./jsoncpp-src-0.5.0/include -I./src -I./ -I./zxing/core/src -I./zxing/cli/src -D DEBUG_PROCESSOR -D DEBUG_ALIGN_IMAGE
-D DEBUG_PROCESSOR -D DEBUG_ALIGN_IMAGE
g++ -Wall -c src/SegmentAligner.cpp -o src/SegmentAligner.o `pkg-config opencv --cflags --libs` -I./jsoncpp-src-0.5.0/include -I./src -I./ -I./zxing/core/src -I./zxing/cli/src -D DEBUG_PROCESSOR -D DEBUG_ALIGN_IMAGE
-D DEBUG_PROCESSOR -D DEBUG_ALIGN_IMAGE
g++ -Wall -c StatCollector.cpp -o StatCollector.o `pkg-config opencv --cflags --libs` -I./jsoncpp-src-0.5.0/include -I./src -I./ -I./zxing/core/src -I./zxing/cli/src -D DEBUG_PROCESSOR -D DEBUG_ALIGN_IMAGE
In file included from StatCollector.cpp:1:0:
StatCollector.h: In constructor ‘StatCollector::StatCollector()’:
StatCollector.h:22:14: warning: ‘StatCollector::numImages’ will be initialized after [-Wreorder]
StatCollector.h:14:5: warning:   ‘int StatCollector::missedSegments’ [-Wreorder]
StatCollector.h:24:2: warning:   when initialized here [-Wreorder]
StatCollector.cpp: In member function ‘void StatCollector::compareFields(const Json::Value&, const Json::Value&, ComparisonMode)’:
StatCollector.cpp:174:3: error: ambiguous overload for ‘operator[]’ in ‘aSegments[0u]’
StatCollector.cpp:174:3: note: candidates are:
./jsoncpp-src-0.5.0/include/json/value.h:277:14: note: Json::Value& Json::Value::operator[](Json::Value::UInt) <near match>
./jsoncpp-src-0.5.0/include/json/value.h:277:14: note:   no known conversion for implicit ‘this’ parameter from ‘const Json::Value_’ to ‘Json::Value_’
./jsoncpp-src-0.5.0/include/json/value.h:281:20: note: const Json::Value& Json::Value::operator[](Json::Value::UInt) const
./jsoncpp-src-0.5.0/include/json/value.h:294:14: note: Json::Value& Json::Value::operator[](const char*) <near match>
./jsoncpp-src-0.5.0/include/json/value.h:294:14: note:   no known conversion for implicit ‘this’ parameter from ‘const Json::Value_’ to ‘Json::Value_’
./jsoncpp-src-0.5.0/include/json/value.h:296:20: note: const Json::Value& Json::Value::operator[](const char*) const
./jsoncpp-src-0.5.0/include/json/value.h:298:14: note: Json::Value& Json::Value::operator[](const string&) <near match>
./jsoncpp-src-0.5.0/include/json/value.h:298:14: note:   no known conversion for implicit ‘this’ parameter from ‘const Json::Value_’ to ‘Json::Value_’
./jsoncpp-src-0.5.0/include/json/value.h:300:20: note: const Json::Value& Json::Value::operator[](const string&) const
StatCollector.cpp:175:3: error: ambiguous overload for ‘operator[]’ in ‘fSegments[0u]’
StatCollector.cpp:175:3: note: candidates are:
./jsoncpp-src-0.5.0/include/json/value.h:277:14: note: Json::Value& Json::Value::operator[](Json::Value::UInt) <near match>
./jsoncpp-src-0.5.0/include/json/value.h:277:14: note:   no known conversion for implicit ‘this’ parameter from ‘const Json::Value_’ to ‘Json::Value_’
./jsoncpp-src-0.5.0/include/json/value.h:281:20: note: const Json::Value& Json::Value::operator[](Json::Value::UInt) const
./jsoncpp-src-0.5.0/include/json/value.h:294:14: note: Json::Value& Json::Value::operator[](const char*) <near match>
./jsoncpp-src-0.5.0/include/json/value.h:294:14: note:   no known conversion for implicit ‘this’ parameter from ‘const Json::Value_’ to ‘Json::Value_’
./jsoncpp-src-0.5.0/include/json/value.h:296:20: note: const Json::Value& Json::Value::operator[](const char*) const
./jsoncpp-src-0.5.0/include/json/value.h:298:14: note: Json::Value& Json::Value::operator[](const string&) <near match>
./jsoncpp-src-0.5.0/include/json/value.h:298:14: note:   no known conversion for implicit ‘this’ parameter from ‘const Json::Value_’ to ‘Json::Value_’
./jsoncpp-src-0.5.0/include/json/value.h:300:20: note: const Json::Value& Json::Value::operator[](const string&) const
make: **\* [StatCollector.o] Error 1

**Comment by wildanm** [comment]
Petunjuk : 

http://forums.codeblocks.org/index.php?topic=13742.0;wap2

**Comment by wildanm** [comment]
Jika baris 174 & 175 di StatColllector.cpp kita comment , proses kompilasi berhasil : 

```
if(aValue.isNull()){
    //assert(!aSegments[size_t(0)].isMember("items")); //ini kita comment sementara
    //assert(!fSegments[size_t(0)].isMember("items")); //ini kita comment sementara
    return;
}
```

**Comment by wildanm** [comment]
Di jsoncpp-src-0.5.0/include/json/value.h 

Pada baris 272 s/d 281 terdapat petunjuk seperti berikut : 

```
  /// Access an array element (zero based index ).
  /// If the array contains less than index element, then null value are inserted
  /// in the array so that its size is index+1.
  /// (You may need to say 'value[0u]' to get your compiler to distinguish
  ///  this from the operator[] which takes a string.)
  Value &operator[]( UInt index );
  /// Access an array element (zero based index )
  /// (You may need to say 'value[0u]' to get your compiler to distinguish
  ///  this from the operator[] which takes a string.)
  const Value &operator[]( UInt index ) const;
```

Ketika mencoba baris 174 & 175 di StatCollector.cpp menjadi : 

```
    assert(!aSegments[0u].isMember("items"));
    assert(!fSegments[0u].isMember("items"));
```

Ternyata proses kompilasi nya berhasil...., akan dilihat, apakah perubahan ini merubah cara kerja ODKScan ?

**Comment by sfranklyn** [comment]
Mustinya tidak ada perubahan karena itu cuma assert alias error check.

**Comment by wildanm** [comment]
Ya, benar @sfranklyn , tidak ada perubahan di cara kerja software nya .., hasil di 32 bit dan 64 bit tetap sama ...

Terimakasih sebelumnya ...
